services:
  - type: web
    name: hempies-coa-sync
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_NAME
        value: Products
      - key: PHP_VERSION
        value: 8.1 